### PR TITLE
Keyboard detection implemented

### PR DESCRIPTION
**Pull request by JoeyAnthony**
Tested and works

### CODE REVIEW

**Comment by JoeyAnthony** [comment]
[(0.5) Keyboard input [1]](https://trello.com/c/Sq5PXmOr/6-0-5-keyboard-input-1)

**Review by StefanMermans — CHANGES_REQUESTED** [review]
Looks pretty good, although I'm not sure if we'll use booleans to check whether a button is pressed, but for now it's fine. 

I would, however, urge you to add documentation and make sure you're upholding the code style. All of the boolean members don't have an underscore in front of them.

**Review by StefanMermans — DISMISSED** [review]

**Review by StefanMermans — CHANGES_REQUESTED** [review]
I would like to see some documentation as well.

**Review by StefanMermans — APPROVED** [review]
accepted, but next time elaborate more in your documentation

**Pull request merged**
